
const data = [
  "Mission: Become a great developer that could create products which can enrich and/or enhance other people's lives.",
  "       Hey! Thanks for visiting my site. Since you've clicked on this link, I'll assume you want to know more about me. I started programming in November 2016. Before that, I never considered being a programmer as a career choice; in high school I was into working out and doing combat sports, such as wrestling and brazilian jiu-jitsu. So I figured I'll pursue a career that is health and fitness related. I got into some colleges and decided to go to UC Davis. ",
  "       At Davis, I studied clinical nutrition and also boxed competitively for the school. After I graduated in 2015, I wasn't really sure of what I should do, so I did a little traveling first. While traveling I thought about my career prospects, if I wanted to be a dietitian, I would have to go to school for another year and it would probably cost me twenty to thirty thousands dollar. Dietitians aren't known for making the most money, so for me, it didn't really make financial sense to pursue that route. Therefore I had to find something else to do.",
  "       After I finished my travels, my student loan payments were coming up, so I took the first job that I could get, which was at a sushi restaurant. While there, I thought about the different careers that I could pursue, e.g doctor, nurse, food service manager, etc. Then one day, I stumbled across an online course that taught the basics of computer science. Before that, my only encounter with computer science was when I used to modify my myspace page. But HTML and CSS isn't really a language right? Anyway, after I finished the course, I like what I saw and decided to pursue this field instead.", 
 "        Once I finished that course, I wanted to study computer science full time. I took other online courses from coursera, edx.org and freecodecamp. I also read a bunch of books about computer science, algorithms, javascript, discrete math and more. I looked at what top universities teach their students in CS programs and convinced myself that I should learn all of these things as well. So far, I haven't touched on all those subjects, but I think I've made decent progress for someone who is self-teaching.",
 "        Now, I've reached a point where I feel confident in my abilities, although I dont know everything, I believe that with enough time and effort, I could become reasonably competent at any subject (as long as it's not anything too crazy of course). I hope to find a company that could see the potential in me and is willing to invest in me. If you would like to get in touch or have any questions, you could shoot me a message on linkedin or at my email. You could also review some of my work on github as well. (see banner above)"
]

export default data;
